### ISSUE TITLE
Beanstalk Language

### ISSUE THREAD

**Issue by s-powell** [axiomzen/contentwren#13]
Beanstalk skills have been adjusted based on feedback. I would greatly appreciate some work on the language.

This doc includes skill tracks for all of AZ in addition to two engineering specific ones:

https://docs.google.com/a/axiomzen.co/spreadsheets/d/1TEFulu8abGdi_iTqQv0rc71w0ITnvTuC9UmEgNwif1E/edit?usp=sharing

**Comment by WrenHandman** [comment]
A few questions that I can't capture in the doc.

1. Is “performant” a developer word, or is that something we should replace with more straightforward language?
2. I’m not sure what you mean by “coupling and cohesion.” under Architecture IV.
3. I’m not sure I understand what architecture means after having read each of these stages. Is it a developer term, or is it a more general project planning term? This section may need some rewording if it is general project management/planning.

@s-powell

**Comment by s-powell** [comment]
> Is “performant” a developer word, or is that something we should replace with more straightforward language?

It's a [word](https://en.oxforddictionaries.com/definition/us/performant) related to computing

> I’m not sure what you mean by “coupling and cohesion.” under Architecture IV.

These are developer jargon. Please leave them as they are.

**Comment by WrenHandman** [comment]
Brilliant! Than this is done.
